FROM elasticsearch:7.6.2
RUN bin/elasticsearch-plugin install analysis-smartcn
RUN bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.6.2/elasticsearch-analysis-ik-7.6.2.zip